name: NPM Publish
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: fluent-cerner-js
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Upgrade npm
        run: npm install -g npm@latest
      - name: Publish
        run: npm publish --provenance --access public
